name: json_widget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-75.1.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  json_schema:
    git: git@github.com:tejainece/json_schema.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  json_schema:
    path: ../json_schema

flutter:
  uses-material-design: true
